# overrides for production environment
# NOTE: docker-compose-prod is not used for Render's production environment
#       Render builds its own docker container
services:
  # Exposed server that's handling incoming web requests
  ohif_viewer:
    volumes:
      # Nginx config
      - ./config/nginx.prod.conf:/etc/nginx/nginx.conf
    env_file:
      - .\..\..\.env
    environment:
      - NODE_ENV=production
